 -- database creation 
 CREATE DATABASE proyectoCoder;
 
 -- databse activation
 USE proyectoCoder;
 
 -- table BRANCHS
CREATE TABLE BRANCHS (
	id_branch INT NOT NULL AUTO_INCREMENT,
    name_branch VARCHAR (45) NOT NULL,
    br_address VARCHAR (100) NOT NULL,
    br_province VARCHAR (20) NOT NULL,
    CONSTRAINT PK_BRANCHS PRIMARY KEY (id_branch)
);


-- table CUSTOMERS
CREATE TABLE CUSTOMERS (
	id_customer INT NOT NULL AUTO_INCREMENT,
    first_name VARCHAR (45) NOT NULL,
    last_name VARCHAR (45) NOT NULL,
    birthday DATE NOT NULL,
    email VARCHAR (45) NOT NULL,
    CONSTRAINT PK_CUSTOMERS PRIMARY KEY (id_customer)
);


-- table CUSTOMIZATIONS
CREATE TABLE CUSTOMIZATIONS (
	id_custom INT NOT NULL AUTO_INCREMENT,
    custom_type VARCHAR (45) NOT NULL,
    CONSTRAINT PK_CUSTOMIZATIONS PRIMARY KEY (id_custom)
);


CREATE TABLE TIME_DELIVERY (
	id_time_del INT NOT NULL,
    time_del_type VARCHAR (20) NOT NULL,
    CONSTRAINT PK_TIME_DELIVERY PRIMARY KEY (id_time_del)
);


-- table ORDER_DETALIS
CREATE TABLE ORDER_DETAILS (
	id_order_details INT NOT NULL AUTO_INCREMENT,
    id_order INT NOT NULL,
    id_product INT NOT NULL,
    quantity INT NOT NULL,
    id_custom INT NOT NULL,
    UNIQUE INDEX UX_ORDER_DETAILS (id_order, id_product),
    CONSTRAINT PK_ORDER_DETAILS PRIMARY KEY (id_order_details)
);


-- table ORDERS
CREATE TABLE ORDERS (
	id_order INT NOT NULL AUTO_INCREMENT,
    id_customer INT NOT NULL,
    date DATETIME NOT NULL,
    id_branch INT NOT NULL,
    id_time_del INT NOT NULL,
    CONSTRAINT PK_ORDERS PRIMARY KEY (id_order)
);


-- table PROD_CATEG
CREATE TABLE PROD_CATEG (
	id_prod_categ INT NOT NULL AUTO_INCREMENT,
    category VARCHAR (45) NOT NULL,
    CONSTRAINT PK_PROD_CATEG PRIMARY KEY (id_prod_categ)
);


-- table PROD_COLOUR
CREATE TABLE PROD_COLOUR (
	id_colour INT NOT NULL AUTO_INCREMENT,
    colour VARCHAR (45) NOT NULL,
    CONSTRAINT PK_PROD_COLOUR PRIMARY KEY (id_colour)
);


-- table PROD_SIZE
CREATE TABLE PROD_SIZE (
	id_size INT NOT NULL AUTO_INCREMENT,
    size VARCHAR(45) NOT NULL,
    CONSTRAINT PK_PROD_SIZE PRIMARY KEY (id_size)
);


-- table PRODUCTS
CREATE TABLE PRODUCTS (
	id_product INT NOT NULL AUTO_INCREMENT,
    stock INT NOT NULL,
    price DECIMAL (6, 2) NOT NULL,
    id_size INT NOT NULL,
    id_colour INT NOT NULL,
    id_prod_categ INT NOT NULL,
    UNIQUE INDEX UX_PRODUCTS (id_size, id_colour, id_prod_categ),
    CONSTRAINT PK_PRODUCT PRIMARY KEY (id_product)
);


-- fk orders to branchs
ALTER TABLE ORDERS 
ADD CONSTRAINT FK_ORDERS_BRANCHS FOREIGN KEY FK_ORDERS_BRANCHS (id_branch)
	REFERENCES BRANCHS (id_branch);


-- fk orders to customers
ALTER TABLE ORDERS 
ADD CONSTRAINT FK_ORDERS_CUSTOMERS FOREIGN KEY FK_ORDERS_CUSTOMERS (id_customer)
	REFERENCES CUSTOMERS (id_customer);


-- fk orders_details to orders
ALTER TABLE ORDER_DETAILS
ADD CONSTRAINT FK_ORDER_DETAILS_ORDERS FOREIGN KEY FK_ORDER_DETAILS_ORDERS (id_order)
	REFERENCES ORDERS (id_order);


-- fk orders_details to products
ALTER TABLE ORDER_DETAILS
ADD CONSTRAINT FK_ORDER_DETAILS_PRODUCTS FOREIGN KEY FK_ORDER_DETAILS_PRODUCTS (id_product)
	REFERENCES PRODUCTS (id_product);


-- fk order_details to customizations
ALTER TABLE ORDER_DETAILS
ADD CONSTRAINT FK_ORDER_DETAILS_CUSTOMIZATIONS FOREIGN KEY FK_ORDER_DETAILS_CUSTOMIZATIONS (id_custom)
	REFERENCES CUSTOMIZATIONS (id_custom);

    
-- fk products to prod_categ
ALTER TABLE PRODUCTS
ADD CONSTRAINT FK_PRODUCTS_PROD_CATEG FOREIGN KEY FK_PRODUCTS_PROD_CATEG (id_prod_categ)
	REFERENCES PROD_CATEG (id_prod_categ);


-- fk products to prod_colour
ALTER TABLE PRODUCTS
ADD CONSTRAINT FK_PRODUCTS_PROD_COLOUR FOREIGN KEY FK_PRODUCTS_PROD_COLOUR (id_colour)
	REFERENCES PROD_COLOUR (id_colour);


-- fk products to prod_size
ALTER TABLE PRODUCTS
ADD CONSTRAINT FK_PRODUCTS_PROD_SIZE FOREIGN KEY FK_PRODUCTS_PROD_SIZE (id_size)
	REFERENCES PROD_SIZE (id_size);


-- fk orders to time_delivery
ALTER TABLE ORDERS
ADD CONSTRAINT FK_ORDER_TIME_DELIVERY FOREIGN KEY FK_ORDER_TIME_DELIVERY (id_time_del)
	REFERENCES TIME_DELIVERY (id_time_del);